import { t } from "../../translations";

export const Strings = {
    appName: () => t('appName'),
    langId: () => t('langId'),
    langNativeName: () => t('langNativeName'),

    placeholderFirstName: () => t('placeholderFirstName'),
    placeholderLastName: () => t('placeholderLastName'),
    placeholderPhoneNumber: () => t('placeholderPhoneNumber'),
    placeholderEmailAddress: () => t('placeholderEmailAddress'),
    placeholderPassword: () => t('placeholderPassword'),
    placeholderDescribeProblem: () => t('placeholderDescribeProblem'),
    placeholderDescribeConcern: () => t('placeholderDescribeConcern'),

    labelFirstName: () => t('labelFirstName'),
    labelLastName: () => t('labelLastName'),
    labelEmailAddress: () => t('labelEmailAddress'),
    labelEmailAddressVerified: () => t('labelEmailAddressVerified'),
    labelPhoneNumber: () => t('labelPhoneNumber'),
    labelPhoneNumberVerified: () => t('labelPhoneNumberVerified'),
    labelYes: () => t('labelYes'),
    labelNo: () => t('labelNo'),

    buttonLogIn: () => t('buttonLogIn'),
    buttonLogOut: () => t('buttonLogOut'),
    buttonBack: () => t('buttonBack'),
    buttonRegister: () => t('buttonRegister'),
    buttonDeleteMyProfile: () => t('buttonDeleteMyProfile'),
    buttonContactSupport: () => t('buttonContactSupport'),
    buttonOK: () => t('buttonOK'),
    buttonAddImageUsingCamera: () => t('buttonAddImageUsingCamera'),
    buttonAddImageFromGallery: () => t('buttonAddImageFromGallery'),
    buttonSubmit: () => t('buttonSubmit'),

    titleGreeting: () => t('titleGreeting'),
    titleAnnouncements: () => t('titleAnnouncements'),
    titleHandymanRequestForm: () => t('titleHandymanRequestForm'),
    titleComplaintSuggestionForm: () => t('titleComplaintSuggestionForm'),
    titleDocumentsAndForms: () => t('titleDocumentsAndForms'),
    titleMembers: () => t('titleMembers'),
    titleBuildingsAndUnits: () => t('titleBuildingsAndUnits'),
    titleInvoices: () => t('titleInvoices'),
    titleSettings: () => t('titleSettings'),
    titleAccounts: () => t('titleAccounts'),

    captionDontHaveAnAccount: () => t('captionDontHaveAnAccount'),
    captionHaveAnAccount: () => t('captionHaveAnAccount'),
    captionEditingUserInfoNotSupportedYet: () => t('captionEditingUserInfoNotSupportedYet'),
    captionAppVersion: () => t('captionAppVersion'),
    captionHereAreAllYourMemberships: () => t('captionHereAreAllYourMemberships'),
    captionPostedOn: () => t('captionPostedOn'),
    captionShareholders: () => t('captionShareholders'),
    captionTenants: () => t('captionTenants'),
    captionShareholderOf: () => t('captionShareholderOf'),
    captionTenantOf: () => t('captionTenantOf'),
    captionVacant: () => t('captionVacant'),
    captionInvoiceDue: () => t('captionInvoiceDue'),
    captionInvoicePaidInFull: () => t('captionInvoicePaidInFull'),
    captionInvoiceSummary: () => t('captionInvoiceSummary'),
    captionInvoiceAmountCharged: () => t('captionInvoiceAmountCharged'),
    captionInvoiceAmountPaid: () => t('captionInvoiceAmountPaid'),
    captionInvoiceAmountDue: () => t('captionInvoiceAmountDue'),
    captionInvoiceURL: () => t('captionInvoiceURL'),
    captionInvoiceLineItems: () => t('captionInvoiceLineItems'),

    actionViewAnnouncements: () => t('actionViewAnnouncements'),
    actionRequestHandyman: () => t('actionRequestHandyman'),
    actionFileComplaint: () => t('actionFileComplaint'),
    actionMakePayment: () => t('actionMakePayment'),
    actionViewOrPayInvoices: () => t('actionViewOrPayInvoices'),
    actionDiscussWithCommunity: () => t('actionDiscussWithCommunity'),
    actionViewDocuments: () => t('actionViewDocuments'),
    actionViewMembers: () => t('actionViewMembers'),
    actionViewBuildingsAndUnits: () => t('actionViewBuildingsAndUnits'),

    errorNeedCameraPermission: () => t('errorNeedCameraPermission'),
    errorNeedGalleryPermission: () => t('errorNeedGalleryPermission'),
    errorNeedCTAInput: () => t('errorNeedCTAInput'),

    messageFormSubmissionSuccessful: () => t('messageFormSubmissionSuccessful'),
};
