export default Strings = {
    appName: 'Rezidy',

    placeholderFirstName: 'First Name',
    placeholderLastName: 'Last Name',
    placeholderPhoneNumber: 'Phone Number',
    placeholderEmailAddress: 'Email Address',
    placeholderPassword: 'Password',
    placeholderDescribeProblem: 'Describe Your Problem',
    placeholderDescribeConcern: 'Describe Your Concern',

    labelFirstName: 'First Name:',
    labelLastName: 'Last Name:',
    labelEmailAddress: 'Email Address:',
    labelEmailAddressVerified: 'Email Address Verified?',
    labelPhoneNumber: 'Phone Number:',
    labelPhoneNumberVerified: 'Phone Number Verified?',
    labelYes: 'Yes',
    labelNo: 'No',

    buttonLogIn: 'Log In',
    buttonLogOut: 'Log Out',
    buttonBack: 'Back',
    buttonRegister: 'Sign Up',
    buttonDeleteMyProfile: 'Delete My Profile',
    buttonContactSupport: 'E-mail Support',
    buttonOK: 'OK',
    buttonAddImageUsingCamera: 'Add Image Using Camera',
    buttonAddImageFromGallery: 'Add Image From Gallery',
    buttonSubmit: 'Submit',

    titleGreeting: 'Hello, %s!',
    titleAnnouncements: 'Announcements',
    titleHandymanRequestForm: 'Handyman Request Form',
    titleComplaintSuggestionForm: 'Complaint/Suggestion Form',
    titleDocumentsAndForms: 'Documents and Forms',
    titleMembers: 'Members',
    titleBuildingsAndUnits: 'Buildings and Units',
    titleInvoices: 'Invoices',

    captionDontHaveAnAccount: 'Don\'t have an account?',
    captionHaveAnAccount: 'Have an account?',
    captionEditingUserInfoNotSupportedYet: 'Editing user info is not supported yet.\nIn the meantime, please contact support for that.',
    captionAppVersion: 'App version %s',
    captionHereAreAllYourMemberships: 'Here are all of the accounts that you are a member of.\nSelect an account to proceed.',
    captionPostedOn: 'Posted on %s',
    captionShareholders: 'Shareholders',
    captionTenants: 'Tenants',
    captionShareholderOf: 'Shareholder of',
    captionTenantOf: 'Tenant of',
    captionVacant: 'Vacant',
    captionInvoiceDue: 'Due',
    captionInvoicePaidInFull: 'Paid in Full',
    captionInvoiceSummary: 'Summary',
    captionInvoiceAmountCharged: 'Amount Charged:',
    captionInvoiceAmountPaid: 'Amount Paid:',
    captionInvoiceAmountDue: 'Amount Due:',
    captionInvoiceURL: 'URL:',
    captionInvoiceLineItems: 'Line Items',

    actionViewAnnouncements: 'View Announcements',
    actionRequestHandyman: 'Request Handyman',
    actionFileComplaint: 'File a Complaint or Suggestion',
    actionMakePayment: 'Make a Payment',
    actionViewOrPayInvoices: 'View or Pay Invoices',
    actionDiscussWithCommunity: 'Discuss with Community',
    actionViewDocuments: 'View Documents and Forms',
    actionViewMembers: 'View Members',
    actionViewBuildingsAndUnits: 'View Buildings and Units',

    errorNeedCameraPermission: 'Permission to access camera is required!',
    errorNeedGalleryPermission: 'Permission to access gallery is required!',
    errorNeedCTAInput: 'Please briefly describe your problem and/or add some images.',

    messageFormSubmissionSuccessful: 'Form submission successful!',
};
