export default Strings = {
    appName: 'Rezidy',

    placeholderFirstName: 'Nombre',
    placeholderLastName: 'Apellido',
    placeholderPhoneNumber: 'Número de teléfono',
    placeholderEmailAddress: 'Dirección de correo electrónico',
    placeholderPassword: 'Contraseña',
    placeholderDescribeProblem: 'Describe tu problema',
    placeholderDescribeConcern: 'Describe tu preocupación',

    labelFirstName: 'Nombre:',
    labelLastName: 'Apellido:',
    labelEmailAddress: 'Dirección de correo electrónico:',
    labelEmailAddressVerified: '¿Dirección de correo electrónico verificada?',
    labelPhoneNumber: 'Número de teléfono:',
    labelPhoneNumberVerified: '¿Número de teléfono verificado?',
    labelYes: 'Sí',
    labelNo: 'No',

    buttonLogIn: 'Iniciar sesión',
    buttonLogOut: 'Cerrar sesión',
    buttonBack: 'Volver',
    buttonRegister: 'Registrarse',
    buttonDeleteMyProfile: 'Eliminar mi perfil',
    buttonContactSupport: 'Soporte por correo electrónico',
    buttonOK: 'OK',
    buttonAddImageUsingCamera: 'Agregar imagen usando la cámara',
    buttonAddImageFromGallery: 'Agregar imagen desde la galería',
    buttonSubmit: 'Enviar',

    titleGreeting: '¡Hola, %s!',
    titleAnnouncements: 'Anuncios',
    titleHandymanRequestForm: 'Formulario de solicitud de trabajos de reparación',
    titleComplaintSuggestionForm: 'Formulario de quejas/sugerencias',
    titleDocumentsAndForms: 'Documentos y formularios',
    titleMembers: 'Miembros',
    titleBuildingsAndUnits: 'Edificios y unidades',
    titleInvoices: 'Facturas',

    captionDontHaveAnAccount: '¿No tienes una cuenta?',
    captionHaveAnAccount: '¿Tienes una cuenta?',
    captionEditingUserInfoNotSupportedYet: 'La edición de la información del usuario aún no es compatible.\nMientras tanto, póngase en contacto con el soporte para eso.',
    captionAppVersion: 'Versión de la aplicación %s',
    captionHereAreAllYourMemberships: 'Aquí están todas las cuentas de las que eres miembro.\nSelecciona una cuenta para continuar.',
    captionPostedOn: 'Publicado el %s',
    captionShareholders: 'Accionistas',
    captionTenants: 'Inquilinos',
    captionShareholderOf: 'Accionista de',
    captionTenantOf: 'Inquilino de',
    captionVacant: 'Vacante',
    captionInvoiceDue: 'Vencimiento',
    captionInvoicePaidInFull: 'Pagado en su totalidad',
    captionInvoiceSummary: 'Resumen',
    captionInvoiceAmountCharged: 'Monto cargado:',
    captionInvoiceAmountPaid: 'Monto pagado:',
    captionInvoiceAmountDue: 'Monto pendiente:',
    captionInvoiceURL: 'URL:',
    captionInvoiceLineItems: 'Ítems de la factura',

    actionViewAnnouncements: 'Ver anuncios',
    actionRequestHandyman: 'Solicitar ayuda',
    actionFileComplaint: 'Presentar una queja o sugerencia',
    actionMakePayment: 'Realizar un pago',
    actionViewOrPayInvoices: 'Ver o pagar facturas',
    actionDiscussWithCommunity: 'Discutir con la comunidad',
    actionViewDocuments: 'Ver documentos y formularios',
    actionViewMembers: 'Ver miembros',
    actionViewBuildingsAndUnits: 'Ver edificios y unidades',

    errorNeedCameraPermission: '¡Se requiere permiso para acceder a la cámara!',
    errorNeedGalleryPermission: '¡Se requiere permiso para acceder a la galería!',
    errorNeedCTAInput: 'Por favor, describe brevemente tu problema y/o agrega algunas imágenes.',

    messageFormSubmissionSuccessful: '¡Envío del formulario exitoso!',
};